export const CC_DELETE_COURSE_CATEGORY = 'CC_DELETE_COURSE_CATEGORY';
export const CC_ADD_COURSE_CATEGORY = 'CC_ADD_COURSE_CATEGORY';
export const CC_SAVE_COURSE_CATEGORY = 'CC_SAVE_COURSE_CATEGORY';
export const CC_SET_SHOW_SPIN = 'CC_SET_SHOW_SPIN';
export const CC_GET_COURSE_CATEGORY = 'CC_GET_COURSE_CATEGORY';
export const CC_GET_COURSE_CATEGORY_SUCCESS = 'CC_GET_COURSE_CATEGORY_SUCCESS';

